version: "3"

services:
  web:
    image: ghcr.io/icefoganalytics/signing-authority:latest
    restart: unless-stopped
    ports:
      - 21557:3000
    environment:
      - AUTH_REDIRECT=${AUTH_REDIRECT}
      - FRONTEND_URL=${FRONTEND_URL}
      - BASE_URL=${BASE_URL}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - ISSUER_BASE_URL=${ISSUER_BASE_URL}
      - SECRET=${SECRET}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_DB=${MONGO_DB}
      - MONGO_FILEBUCKET=${MONGO_FILEBUCKET}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - NODE_ENV=${NODE_ENV}
      - API_GATEWAY_KEY=${API_GATEWAY_KEY}
      - VUE_APP_FRONTEND_URL=${VUE_APP_FRONTEND_URL}
      - VUE_APP_AUTH_DOMAIN=${VUE_APP_AUTH_DOMAIN}
      - VUE_APP_AUTH_CLIENTID=${VUE_APP_AUTH_CLIENTID}
      - VUE_APP_AUTH_AUDIENCE=${VUE_APP_AUTH_AUDIENCE}
      - AD_CLIENT_ID=${AD_CLIENT_ID}
      - AD_CLIENT_SECRET=${AD_CLIENT_SECRET}
      - AD_TENANT_ID=${AD_TENANT_ID}
      - FM_ACCOUNT_LOOKUP_URL=${FM_ACCOUNT_LOOKUP_URL}
      - FM_ACCOUNT_LOOKUP_KEY=${FM_ACCOUNT_LOOKUP_KEY}
      - APPLICATION_NAME=${APPLICATION_NAME}
      - SUSPEND_EMAIL=${SUSPEND_EMAIL}

  mongodb:
    image: mongo:5.0.6
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - TZ=America/Whitehorse
    volumes:
      - mongo-data:/data/db
      - ./dump:/dump

volumes:
  mongo-data: