version: "3"

services:
  db: 
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports: 
      - "1433:1433"
    env_file: 
      - db/sqlserver.env
      - db/sapassword.env
    user: root
    volumes:
      - sqldata:/var/opt/mssql/data
      - sqllog:/var/opt/mssql/log
      - ./db/backups/:/var/opt/sqlserver/backup

volumes:
  sqldata:
  sqllog:
