apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-data
  name: mongo-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: tanzu-vsan
  resources:
    requests:
      storage: 1Gi
status: {}
